"""Add many to many model

Revision ID: 3e461cb173f4
Revises: 98b1b4398c0b
Create Date: 2023-06-02 22:01:34.625852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e461cb173f4'
down_revision = '98b1b4398c0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
